language: php
php:
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer install --dev --prefer-source --no-interaction
  - "mysql -e 'create database codeception_test;'"
  - php artisan migrate --no-interaction

script:
  - php vendor/bin/codecept run --env
  - php vendor/bin/codecept run functional --env

notifications:
  slack: informulate:Io7yxfri2SwOzQ0h3KUG4OFB
